name: Release - PyDev

on:
  push:
    branches:
      - "release-pydev"
      
jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
          
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
          cache: 'maven'
          
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8.12
          
      - name: Set up Python 3.8 deps
        run: |
            python3 -m pip install cython numpy zope.interface

      - name: Print Python/Java info
        run: |
            echo ---- 
            echo ----
            which python3
            python3 -c "import numpy;print(numpy.__version__, numpy.__file__)"
            python3 -c "import django;print(django.__file__)"
            python3 -c "import hmac;print(hmac.__file__)"
            echo SKIPPED python3 -c "import PyQt5;print(PyQt5.__file__)"
            python3 plugins/org.python.pydev.core/pysrc/interpreterInfo.py
            
            echo ---- 
            echo ----
            which java
            which mvn
            echo ---- rt.jar should be listed below
            find /opt/hostedtoolcache/Java_Adopt_jdk/11.0.18-10/x64/ -name "*.jar"
            
      - name: xvfb
        shell: bash
        env:
          DISPLAY: ":99.0"
        run: |
          sudo apt install libxkbcommon-x11-0 libxcb-icccm4 libxcb-image0 libxcb-keysyms1 libxcb-randr0 libxcb-render-util0 libxcb-xinerama0 libxcb-xfixes0
          /sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -screen 0 1920x1200x24 -ac +extension GLX

        
      - name: Build with Maven
        run: mvn install -DskipTests=true

        